AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.
Resources:
  myDateTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: awslambdafunctionwithpython
      CodeUri: s3://aws-lambda-function-python/8359c7b64fac62ec56bab10911d907ff
      Handler: app.handler
      Runtime: python3.8
      Layers:
      - Ref: Layer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /path
            Method: get
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource: '*'
    Metadata:
      SamResourceId: myDateTimeFunction
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pocket-readtime-tagger-layer
      Description: Lambda layer with libs like pocket and datetime
      ContentUri: s3://aws-lambda-function-python/abf2fa069416b4db1a3e7b65ece2cd5d
    Metadata:
      SamResourceId: Layer
