version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-aws-lambda-python"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lwtdplov1gzb"
s3_prefix = "sam-app-aws-lambda-python"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
